#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=24:00:00
#PBS -N app-mriqc

rm -rf output

T1=`jq -r '.t1' config.json`

#copy input t1 under input in bids format
mkdir -p input/sub-0/anat output
ln -s $T1 input/sub-0/anat/sub-0_T1w.nii.gz

module load singularity 2> /dev/null

#temporary patch until latest container is published
#time singularity exec docker://poldracklab/mriqc bash -c "ldconfig && /usr/local/miniconda/bin/mriqc input output participant --no-sub"
time singularity run docker://soichih/mriqc input output participant --no-sub

#check for output files
if [ -f output/reports/sub-0_T1w.html ]; then
    exit 0
else
	echo "reports directory is empty"
	exit 1
fi

