#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=24:00:00
#PBS -N app-mriqc

rm -rf output

set -e
set -x

#copy input t1 under input in bids format
mkdir -p input/sub-0/anat output
ln -sf ../../../$(jq -r '.t1' config.json) input/sub-0/anat/sub-0_T1w.nii.gz
cat > input/dataset_description.json <<EOF
{
    "BIDSVersion": "1.0.0",
    "Name": "Temp dataset",
    "Authors": [
        "Soichi Hayashi"
    ]
}
EOF

time singularity exec docker://poldracklab/mriqc:0.15.1 mriqc input output participant --no-sub


